name: Build and Publish Docker
on:
  push:
    branches:
      # Only commits to master trigger build
      - main
    paths-ignore:
      # Don't trigger build on README.md change
      - 'README.md'
  workflow_dispatch:
  schedule:
    # UTC schedule
    #        M H DOM MONTH DAY
    - cron: "0 2 *   *     SUN"
jobs:
  # Ideally these would be de-duplicated with yaml anchors, but that's not supported yet:
  # https://github.community/t5/GitHub-Actions/Support-for-YAML-anchors/td-p/30336
  build_latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Version strings
      id: version
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
      run: |
        echo "RELEASE_TIME=$(date +"%y-%m-%d-%H-%M")" >> $GITHUB_ENV         

    - name: Publish to Docker Repository (latest)
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: prismaticd/prefect-base
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.RELEASE_TIME }}"
